export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const SHOW_MENU_ITEMS = 'SHOW_MENU_ITEMS';
export const SHOW_MENU_ERROR = 'SHOW_MENU_ERROR';
export const SHOW_MENU_SUCCESSFUL = 'SHOW_MENU_SUCCESSFUL';